name: sound_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  pixelarticons: ^0.4.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
# Para incluir fuentes personalizadas
  fonts:
    - family: KiwiSoda # Un nombre para tu familia de fuentes
      fonts:
        - asset: assets/fonts/KiwiSoda.ttf